<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ollama-Blazor</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.40.0" />
    <PackageReference Include="Markdig.SyntaxHighlighting" Version="1.1.7" />
    <PackageReference Include="Markdown.ColorCode" Version="3.0.0" />
    <PackageReference Include="OllamaSharp" Version="5.1.13" />
  </ItemGroup>

</Project>
